[theme]
primaryColor = "#238636"
backgroundColor = "#0d1117"
secondaryBackgroundColor = "#161b22"
textColor = "#c9d1d9"
font = "sans serif"

[server]
maxUploadSize = 200

[browser]
gatherUsageStats = false
